### ISSUE TITLE
'NoneType' object has no attribute 'autogenerate'

### ISSUE THREAD

**Issue by Corfucinas** [sqlalchemy/alembic#1088]
**Describe the bug**
Creating an automatic revision using

```python
command.revision(
                Config('./alembic.ini'),
                message='automated_revision',
                autogenerate=True,
            )
```

will fail with ` 'NoneType' object has no attribute 'autogenerate'` if the `env.py` file follows the [cookbook 'Don't Generate Empty Migrations with Autogenerate'](https://alembic.sqlalchemy.org/en/latest/cookbook.html#don-t-generate-empty-migrations-with-autogenerate). The rest of the `env.py` is the same as the one generated by Alembic, except for introducing `run_migrations_online()`.

**Expected behavior**
A migration will be generated and applied if a change in the model is introduced when running the python code, a migration will not be generated if the model is the same as the last run.

**To Reproduce**

`model.py`

```python
# -*- coding: utf-8 -*-
"""Dataclass for database ORM."""

# built-in
from datetime import datetime

# external
from sqlmodel import Field, SQLModel, String


class SimpleModel(SQLModel, table=True):
    __tablename__ = "model"
    id: int = Field(primary_key=True)
    name: str | None = Field(index=True)
    age: str | None = Field(index=True)
```

`main.py`
```python
from alembic import command
from alembic.config import Config

alembic_cfg = Config('./alembic.ini')

command.revision(
    alembic_cfg,
    message='first_revision',
    autogenerate=True,
)

```

`env.py`
```python
# -*- coding: utf-8 -*-
"""Alembic script for handling migrations."""

# built-in
from logging.config import fileConfig

# external
from alembic import context, migration
from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel

from model import SimpleModel

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    def process_revision_directives(
        context: migration.MigrationContext, revision: tuple[str], directives
    ) -> None:

        if config.cmd_opts.autogenerate:
            script = directives[0]
            if script.upgrade_ops.is_empty()
                directives[:] = []

    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            process_revision_directives=process_revision_directives,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()

```

</details>

**Versions.**
 - OS: `Linux 5.15.0-50-generic x86_64`
 - Python: `3.10.2`
 - Alembic: `1.8.1`
 - SQLAlchemy: `1.4.41`
 - Database: `Sqlite`
 - DBAPI:

**Error**

<details open>
<summary>Stack trace</summary>
```

Traceback (most recent call last):
  File "/home/Github/./src/main.py", line 157, in <module>
    asyncio.run(main())
  File "/home/.pyenv/versions/3.10.2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/Github/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 1212, in catch_wrapper
    return await function(*args, **kwargs)
  File "/home/Github/./src/main.py", line 133, in main
    sqlite_database = SqliteDatabase(
  File "/home/Github/src/database.py", line 64, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/home/Github/src/database.py", line 96, in __init__
    self._create_tables()
  File "/home/Github/src/database.py", line 108, in _create_tables
    command.revision(
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/command.py", line 229, in revision
    script_directory.run_env()
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/Github/migrations/env.py", line 113, in <module>
    run_migrations_online()
  File "/home/Github/migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/Github//.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/command.py", line 205, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 526, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/Github/.venv/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 584, in _run_environment
    hook(migration_context, rev, self.generated_revisions)
  File "/home/Github/migrations/env.py", line 86, in process_revision_directives
    if config.cmd_opts.autogenerate:
AttributeError: 'NoneType' object has no attribute 'autogenerate'

```

**Comment by Corfucinas** [comment]
commenting out

```python
context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # process_revision_directives=process_revision_directives,
        )
```

will make it work, however it will result in an empty migration every time the code is run.
