### ISSUE TITLE
Bug in docs example throws Error InvalidSchemaName even if the schema name is valid and exists.

### ISSUE THREAD

**Issue by alispa** [sqlalchemy/alembic#1096]
**Describe the bug**
Alembic tenant is not case sensitive and, if a schema name has uppercase chars, it throws an error (schema not found).

I have used this [alembic tutorial (cookbook) on using support for multiple schemas in Postgres](https://alembic.sqlalchemy.org/en/latest/cookbook.html#rudimental-schema-level-multi-tenancy-for-postgresql-databases).

I use Postgres and my schema name is `'John'`.

If I run `alembic -x tenant=John upgrade head` I get an error:
`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in...`

It works if my schema name is lowercase 'john' and If I run `alembic -x tenant=john upgrade head` .

**How to fix it:**

In this line of the cookbook example:
`connection.execute("set search_path to %s" % current_tenant)`

wrap the `%s` into quotes or double quotes like this:
`connection.execute("set search_path to '%s'" % current_tenant)`
or this
`connection.execute('set search_path to "%s"' % current_tenant)`

Solution hint:
This [answer](https://dba.stackexchange.com/a/195560/200208) on stackexchange.

**Expected behavior**
The tenant (schema name) should be case sensitive.

**To Reproduce**
Use this [alembic tutorial (cookbook) on using support for multiple schemas in Postgres](https://alembic.sqlalchemy.org/en/latest/cookbook.html#rudimental-schema-level-multi-tenancy-for-postgresql-databases).

To get an error:
Create a Postgres schema named `'John'`.
Run `alembic -x tenant=John upgrade head` 

To get an succeed:
Create a Postgres schema named `'john'`.
Run `alembic -x tenant=john upgrade head` 

**Error**

```
(venv) PS C:\Users\Asus\Desktop\kerp_dev\backend\apps> alembic -x tenant=John upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidSchemaName: no schema has been selected to create in
LINE 2: CREATE TABLE alembic_version (
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\config.py", line 561, in run_cmd
    fn(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\command.py", line 322, in upgrade
    script.run_env()
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\script\base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Asus\Desktop\kerp_dev\backend\apps\alembic\env.py", line 99, in <module>
    run_migrations_online()
  File "C:\Users\Asus\Desktop\kerp_dev\backend\apps\alembic\env.py", line 93, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\runtime\environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\runtime\migration.py", line 606, in run_migrations
    self._ensure_version_table()
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\alembic\runtime\migration.py", line 542, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 950, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\sql\ddl.py", line 893, in visit_table
    self.connection.execute(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\sql\ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Asus\Desktop\kerp_dev\venv\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
LINE 2: CREATE TABLE alembic_version (
                     ^

[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Versions.**
 - OS: Windows 11 (build 22000.1042)
 - Python: 3.10.7
 - Alembic: 1.8.1
 - SQLAlchemy: 1.4.29
 - Database: Postgres 14
 - DBAPI: psycopg2

**Comment by CaselIT** [comment]
Hi,

thanks for reporting. If you can make a PR to fix the cookbook it would be appreciated.
I think we should use the second form `connection.execute('set search_path to "%s"' % current_tenant)` since identifiers in PostgreSQL use `"`

**Comment by mgurg** [comment]
Hi,
I don't know if my today problem is related, but I have a error in the same area. With SQLAlchemy "1.4.x" everything was fine, after a switch to SQLAlchemy = "2.0.0b1" I am receiving:

```bash
web_1  | Not an executable object: 'set search_path to "public"'
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1388, in execute
web_1  |     meth = statement._execute_on_connection
web_1  | AttributeError: 'str' object has no attribute '_execute_on_connection'
web_1  | 
web_1  | The above exception was the direct cause of the following exception:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/src/./app/service/tenants.py", line 55, in alembic_upgrade_head
web_1  |     command.upgrade(config, revision, sql=sql, tag=tag)
web_1  |   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
web_1  |     script.run_env()
web_1  |   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
web_1  |     util.load_python_file(self.dir, "env.py")
web_1  |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
web_1  |     module = load_module_py(module_id, path)
web_1  |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
web_1  |     spec.loader.exec_module(module)  # type: ignore
web_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
web_1  |   File "/src/migrations/env.py", line 103, in <module>
web_1  |     run_migrations_online()
web_1  |   File "/src/migrations/env.py", line 84, in run_migrations_online
web_1  |     connection.execute('set search_path to "%s"' % current_tenant)
web_1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1390, in execute
web_1  |     raise exc.ObjectNotExecutableError(statement) from err
web_1  | sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'set search_path to "public"'
```

Code ( [Github repo](https://github.com/mgurg/fastapi_docker/blob/main/migrations/env.py)):

```python
def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    current_tenant = context.get_x_argument(as_dictionary=True).get("tenant")
    dry_run = context.get_x_argument(as_dictionary=True).get("dry_run")

    with connectable.connect() as connection:
        connection.execute('set search_path to "%s"' % current_tenant)
        connection.dialect.default_schema_name = current_tenant

        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table_schema=current_tenant,
        )

        with context.begin_transaction() as transaction:
            context.run_migrations()
```
**Versions.**
- OS: Pop_os 22.04
- Python: 3.10.7
- Alembic: 1.8.1
- SQLAlchemy: 1.4.42/2.0.0b1
- Database: Postgres 14
- DBAPI: psycopg2

**Comment by zzzeek** [comment]
I will fix both doc issues now, but note if you're going to  "switch" to 2.0 from an existing 1.4 application, you need to go through the [migration path](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#x-2-x-migration-overview) which will emit warnings under 1.4 for all APIs that need to change first.
