### ISSUE TITLE
Alembic init doesn't work with SQLalchemy 2

### ISSUE THREAD

**Issue by evilhamsterman** [sqlalchemy/alembic#1198]
**Describe the bug**
`alembic init`  fails with sqlalchemy 2.0.5.post1 and possibly other sqlalchemy 2 versions

**Expected behavior**
`alembic init` creates a folder for migrations

**To Reproduce**
Install alembic with pip without sqlalchemy first or install sqlalchemy 2 with alembic

**Error**

```
sh$ alembic init migrations
Traceback (most recent call last):
  File "/home/vscode/.local/bin/alembic", line 5, in <module>
    from alembic.config import main
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/__init__.py", line 4, in <module>
    from . import context  # noqa
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 15, in <module>
    from .. import ddl
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql  # noqa
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/ddl/mssql.py", line 8, in <module>
    from .base import AddColumn
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/ddl/base.py", line 9, in <module>
    from .. import util
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/util/__init__.py", line 24, in <module>
    from .sqla_compat import sqla_09  # noqa
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/util/sqla_compat.py", line 11, in <module>
    from sqlalchemy.sql.expression import _BindParamClause
ImportError: cannot import name '_BindParamClause' from 'sqlalchemy.sql.expression' (/home/user/.local/lib/python3.10/site-packages/sqlalchemy/sql/expression.py)
```

**Versions.**
 - OS: Ubuntu 22.04
 - Python: 3.10
 - Alembic: 1.10.2
 - SQLAlchemy: 2.0.5.post1
 - Database: NA
 - DBAPI: NA

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

this is not alembic 1.10.2:

    File "/home/vscode/.local/lib/python3.10/site-packages/alembic/util/__init__.py", line 24, in <module>
       from .sqla_compat import sqla_09  # noqa

There's no such thing in that file, that looks more like [alembic 1.0.6](https://github.com/sqlalchemy/alembic/blob/54099921a919f74d7c29a24e88214f95e9878a44/alembic/util/__init__.py#L24).   SQLAlchemy 0.9 has not been referenced in the source code for many years.  

you'd want to check your paths  / installation.

**Comment by evilhamsterman** [comment]
I tried this across several different VMs and platforms and ran into the
same issue. I did not install an older version of alembic I just ran the
command pip install alembic in a clean environment. So unless the default
version pip pulls is 1.0.6 and pip lost lies to me it is 1.10.2

**Comment by zzzeek** [comment]
can you show the output of the pip command?

are you using some special pip options or running it with a local registry ?
