### ISSUE TITLE
Error When there is an @ symbol in the password. error: invalid interpolation syntax in %r at 

### ISSUE THREAD

**Issue by greper** [sqlalchemy/alembic#1279]
**Describe the bug**
Error When there is an @ symbol in the password

urlencode('@') = %40

Abc@1234567 =  Abc%401234567

**Expected behavior**
```
execute success
```

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```shell
alembic upgrade head
```

**Error**

```
alembic upgrade head
Traceback (most recent call last):
  File "D:\Soft\Development\Python3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Soft\Development\Python3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Codes\powerleader\pl-cs\backend\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\config.py", line 603, in run_cmd
    fn(
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\command.py", line 385, in upgrade
    script.run_env()
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\script\base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\util\pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\util\pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Codes\powerleader\pl-cs\backend\src/repository/migrations\env.py", line 14, in <module>
    config.set_main_option(name="sqlalchemy.url", value=str(async_db.postgres_uri))
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\config.py", line 272, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "D:\Codes\powerleader\pl-cs\backend\venv\lib\site-packages\alembic\config.py", line 299, in set_section_option
    self.file_config.set(section, name, value)
  File "D:\Soft\Development\Python3.10\lib\configparser.py", line 1206, in set
    super().set(section, option, value)
  File "D:\Soft\Development\Python3.10\lib\configparser.py", line 896, in set
    value = self._interpolation.before_set(self, section, option,
  File "D:\Soft\Development\Python3.10\lib\configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'postgresql://root:Abc%401234567@192.168.43.240:5432/db_name' at position 23

```

**Versions.**
 - OS:  windows
 - Python:  3.10
 - Alembic: 1.11.1
 - SQLAlchemy: 2.0.19
 - Database: postgreSQL
 - DBAPI:

**Comment by CaselIT** [comment]
Hi,

Since the config file parser is parted using config parser you need to escape the `%` using two of them, as explained in the std lib https://docs.python.org/3/library/configparser.html?highlight=configparser#configparser.BasicInterpolation
