### ISSUE TITLE
Sqlite drop table operation not rollbacked

### ISSUE THREAD

**Issue by vtgn** [sqlalchemy/alembic#1553]
**Describe the bug**
Hello,
I test the transactional feature during migrations of alembic with a SQLite database, but during a downgrade, if an error occurs after a drop table operation, a rollback is done but the table is still deleted in the database. And since the migration's version in the _alembic_version_ table has not been updated because of the error, the DB is in a corrupted state (the stored alembic version is invalid for the current DB schema).

**Expected behavior**
The dropped table should be still present after the rollback.

**To Reproduce**
- Create a SQLAlchemy model for a table.
- Create a default alembic workspace (single-database configuration).
- Set the sqlalchemy.url property with a DB URL to a SQLite database (sqlite:///<path>/mydb.db)
- In the env.py module:
    - set _target_metadata_ with the metadata owning your model class
    - add the properties arguments _transactional_ddl=True, transaction_per_migration=False_ into the _context.configure(...)_ calls
- Create a revision file: _alembic revision --autogenerate_
- Modify this revision file, to add a statement generating an error during the downgrade after the drop of the table (ex. by adding a drop table command on a non existing table)
- Upgrade the sqlite database: _alembic upgrade head_
- Downgrade the sqlite database to the base revision: _alembic downgrade base_

Here is my revision file:
```py
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1.0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", name="user_gender_model_enum", create_constraint=True),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person")
    # ### end Alembic commands ###

    op.drop_table("toto") # I added this command manually to provoke an error during the SQL transaction of the downgrade
```
Here is my env.py file main methods:
```py
...
def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        transactional_ddl=True,
        transaction_per_migration=False,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            transactional_ddl=True,
            transaction_per_migration=False,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
```
**Error**
Here are all the DEBUG logs generated during the _alembic downgrade base_ command:
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [sqlalchemy.engine.Engine] BEGIN (implicit)
INFO  [sqlalchemy.engine.Engine] PRAGMA main.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
DEBUG [sqlalchemy.engine.Engine] Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
DEBUG [sqlalchemy.engine.Engine] Row (0, 'version_num', 'VARCHAR(32)', 1, None, 1)
INFO  [sqlalchemy.engine.Engine] SELECT alembic_version.version_num
FROM alembic_version
INFO  [sqlalchemy.engine.Engine] [generated in 0.00035s] ()
DEBUG [sqlalchemy.engine.Engine] Col ('version_num',)
DEBUG [sqlalchemy.engine.Engine] Row ('1.0',)
INFO  [alembic.runtime.migration] Running downgrade 1.0 -> , Migration script for initial revision v1.0.
INFO  [sqlalchemy.engine.Engine]
DROP TABLE user
INFO  [sqlalchemy.engine.Engine] [no key 0.00029s] ()
INFO  [sqlalchemy.engine.Engine] 
DROP TABLE toto
INFO  [sqlalchemy.engine.Engine] [no key 0.00048s] ()
INFO  [sqlalchemy.engine.Engine] ROLLBACK
Traceback (most recent call last):
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: toto

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\myapp\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "C:\myapp\venv\Lib\site-packages\alembic\config.py", line 636, in main
    CommandLine(prog=prog).main(argv=argv)
  File "C:\myapp\venv\Lib\site-packages\alembic\config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "C:\myapp\venv\Lib\site-packages\alembic\config.py", line 603, in run_cmd
    fn(
  File "C:\myapp\venv\Lib\site-packages\alembic\command.py", line 453, in downgrade        
    script.run_env()
  File "C:\myapp\venv\Lib\site-packages\alembic\script\base.py", line 586, in run_env      
    util.load_python_file(self.dir, "env.py")
  File "C:\myapp\venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myapp\venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\myapp\alembic\env.py", line 87, in <module>
    run_migrations_online()
  File "C:\myapp\alembic\env.py", line 81, in run_migrations_online     
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\myapp\venv\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\myapp\venv\Lib\site-packages\alembic\runtime\migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "C:\myapp\alembic\versions\20241023_v1.0.py", line 53, in downgrade
    op.drop_table("toto")
  File "<string>", line 8, in drop_table
  File "<string>", line 3, in drop_table
  File "C:\myapp\venv\Lib\site-packages\alembic\operations\ops.py", line 1422, in drop_table
    operations.invoke(op)
  File "C:\myapp\venv\Lib\site-packages\alembic\operations\base.py", line 442, in invoke   
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\myapp\venv\Lib\site-packages\alembic\operations\toimpl.py", line 88, in drop_table
    operations.impl.drop_table(
  File "C:\myapp\venv\Lib\site-packages\alembic\ddl\impl.py", line 392, in drop_table      
    self._exec(schema.DropTable(table, **kw))
  File "C:\myapp\venv\Lib\site-packages\alembic\ddl\impl.py", line 210, in _exec
    return conn.execute(construct, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute  
    return meth(
           ^^^^^
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\sql\ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1529, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\myapp\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: toto
[SQL:
DROP TABLE toto]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
Although the logs indicate a ROLLBACK in an opened SQL transaction, the table is still deleted in the database file at the end of the command.
Did I forget something?

**Versions.**
 - OS: Windows 11 Enterprise
 - Python: 3.12.6
 - Alembic: 1.13.3
 - SQLAlchemy: 2.0.35
 - Database: SQLite
 - DBAPI: sqlite3

**Additional context**
None.

Thanks.

**Have a nice day!**

**Comment by vtgn** [comment]
Another thing I don't understand: why the SQL transaction is still created during a upgrade()/downgrade() with the configuration _transactional_ddl=False, transaction_per_migration=False_ ?
The documentation of the _context.begin_transaction()_ specifies:

> If :meth:`.is_transactional_ddl` is ``False``,
      returns a "do nothing" context manager
      which otherwise produces no transactional
      state or directives.

So why the debug logs of _sqlalchemy.engine.Engine_ still show a transaction is opened and closed?

**Comment by vtgn** [comment]
I try several things, and I get some very strange behaviors, like this one:

```
$ alembic upgrade head
INFO  [sqlalchemy.engine.Engine] BEGIN (implicit)
INFO  [sqlalchemy.engine.Engine] PRAGMA foreign_keys=ON
INFO  [sqlalchemy.engine.Engine] [generated in 0.00083s] ()
INFO  [sqlalchemy.engine.Engine] PRAGMA journal_mode=WAL
INFO  [sqlalchemy.engine.Engine] [generated in 0.00031s] ()
DEBUG [sqlalchemy.engine.Engine] Col ('journal_mode',)
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [sqlalchemy.engine.Engine] PRAGMA main.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
DEBUG [sqlalchemy.engine.Engine] Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
INFO  [sqlalchemy.engine.Engine] PRAGMA temp.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
DEBUG [sqlalchemy.engine.Engine] Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
INFO  [sqlalchemy.engine.Engine] PRAGMA main.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
DEBUG [sqlalchemy.engine.Engine] Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
INFO  [sqlalchemy.engine.Engine] PRAGMA temp.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
DEBUG [sqlalchemy.engine.Engine] Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
INFO  [sqlalchemy.engine.Engine]
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)


INFO  [sqlalchemy.engine.Engine] [no key 0.00039s] ()
INFO  [alembic.runtime.migration] Running upgrade  -> 1.0, Migration script for initial revision v1.0.
INFO  [sqlalchemy.engine.Engine]
CREATE TABLE person (
        name VARCHAR NOT NULL,
        gender VARCHAR(6) NOT NULL,
        id INTEGER NOT NULL,
        created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
        PRIMARY KEY (id),
        CONSTRAINT person_gender_model_enum CHECK (role IN ('MALE', 'FEMALE'))
)


INFO  [sqlalchemy.engine.Engine] [no key 0.00078s] ()
DEBUG [alembic.runtime.migration] new branch insert 1.0
INFO  [sqlalchemy.engine.Engine] INSERT INTO alembic_version (version_num) VALUES ('1.0') RETURNING version_num
INFO  [sqlalchemy.engine.Engine] [generated in 0.00022s] ()
DEBUG [sqlalchemy.engine.Engine] Col ('version_num',)
DEBUG [sqlalchemy.engine.Engine] Row ('1.0',)
INFO  [alembic.runtime.migration] Running upgrade 1.0 -> 1.1, Migration script from v1.0 to v1.1.
INFO  [sqlalchemy.engine.Engine]
DROP TABLE person
INFO  [sqlalchemy.engine.Engine] [no key 0.00018s] ()
DEBUG [alembic.runtime.migration] update 1.0 to 1.1
INFO  [sqlalchemy.engine.Engine] UPDATE alembic_version SET version_num='1.1' WHERE alembic_version.version_num = '1.0'
INFO  [sqlalchemy.engine.Engine] [generated in 0.00027s] ()
INFO  [sqlalchemy.engine.Engine] ROLLBACK
$ echo $?
0
```

I don't know what I did particularly for this case, but the command finished with the 0 code, which means OK, but the logs show the SQL transaction finished by a ROLLBACK, and in the database file, the table person is still created, but there is no version created in the alembic_version table. So it proves that the INSERT INTO and the UPDATE commands have been rollbacked, but not the two CREATE TABLE. And I still don't know why a transaction is created...
