### ISSUE TITLE
support explicit encoding for generated source files

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#198]
**Migrated issue, originally created by Teemu ([@Frozenball](https://github.com/Frozenball))**

Creating a migration with non-ascii characters is not possible. Example:
````
$ alembic revision -m 'Testing äåö'
  Generating /Users/teemu/Documents/pelsu/pelsu/migrations/versions/1c1ab19e6708_testing.py ... FAILED
Traceback (most recent call last):
  File "/Users/teemu/.virtualenvs/pelsu/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.6.4', 'console_scripts', 'alembic')()
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/config.py", line 298, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/config.py", line 293, in main
    self.run_cmd(cfg, options)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/config.py", line 279, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/command.py", line 99, in revision
    **template_args)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/script.py", line 352, in generate_revision
    **kw
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/script.py", line 315, in _generate_template
    **kw
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/util.py", line 167, in status
    ret = fn(*arg, **kw)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/alembic/util.py", line 53, in template_to_file
    Template(filename=template_file).render(**kw)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/teemu/.virtualenvs/pelsu/lib/python2.7/site-packages/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "pelsu_migrations_script_py_mako", line 29, in render_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
````

**Comment by zzzeek** [comment]
there is no issue on Python 3.  as Python 2 is EOL, closing this.

```
$ PYTHONPATH=~/dev/sqlalchemy/lib/ python -m alembic.config revision -m 'Testing äåö'
  Generating /home/classic/dev/alembic/foo/versions/9ed5cd40efcc_testing_äåö.py ...  done
  Running post write hook "black" ...
reformatted /home/classic/dev/alembic/foo/versions/9ed5cd40efcc_testing_äåö.py
All done! ✨ 🍰 ✨
1 file reformatted.
  done
  Running post write hook "zimports" ...
[Writing]       /home/classic/dev/alembic/foo/versions/9ed5cd40efcc_testing_äåö.py ([18% of lines are imports] [source +0L/-1L] [1 imports removed in 0.0025 sec])
  done
[classic@photon3 alembic]$ vi foo/versions/9ed5cd40efcc_testing_äåö.py 
[classic@photon3 alembic]$ PYTHONPATH=~/dev/sqlalchemy/lib/ python -m alembic.config upgrade head
INFO  [sqlalchemy.engine.base.Engine] select version()
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [sqlalchemy.engine.base.Engine] select current_schema()
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [sqlalchemy.engine.base.Engine] SELECT CAST('test plain returns' AS VARCHAR(60)) AS "'test plain returns'"
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [sqlalchemy.engine.base.Engine] SELECT CAST('test unicode returns' AS VARCHAR(60)) AS "'test unicode returns'"
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [sqlalchemy.engine.base.Engine] show standard_conforming_strings
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [sqlalchemy.engine.base.Engine] BEGIN (implicit)
INFO  [sqlalchemy.engine.base.Engine] select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
INFO  [sqlalchemy.engine.base.Engine] {'name': 'alembic_version'}
INFO  [sqlalchemy.engine.base.Engine] SELECT alembic_version.version_num 
FROM alembic_version
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [alembic.runtime.migration] Running upgrade 67fc47d69418 -> 9ed5cd40efcc, Testing äåö
INFO  [sqlalchemy.engine.base.Engine] UPDATE alembic_version SET version_num='9ed5cd40efcc' WHERE alembic_version.version_num = '67fc47d69418'
INFO  [sqlalchemy.engine.base.Engine] {}
INFO  [sqlalchemy.engine.base.Engine] COMMIT
[classic@photon3 alembic]$ 


```
