### ISSUE TITLE
Autogenerate fails on functional index with sqlite

### ISSUE THREAD

**Issue by KPilnacek** [sqlalchemy/alembic#523]
Hello there,

I have a following table:
```python
from sqlalchemy import Column, Integer, String, Index, func,
from sqlalchemy.ext.declarative import declarative_base

class Base(object):
    id = Column(Integer, primary_key=True)

    def __repr__(self):
        return f'{self.__class__.__name__}({self.id})'

Base = declarative_base(cls=Base)

class Supplier(Base):
    __tablename__ = "suppliers"
    id = Column(String(length=20), primary_key=True)  # noqa: A003
    name = Column(String(), index=True)
```

with functional index defined as follows:
```python
Index(
    "supplier_name_idx",
    func.replace(func.replace(func.replace(func.lower(Supplier.name), ".", ""), " ", ""), ",", ""),
)
```
Now, if try to run `alembic revision --autogenerate`, it throws the following warning for postgres:
```shell
/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/util/messaging.py:70: UserWarning: autogenerate skipping functional index supplier_name_idx; not supported by SQLAlchemy reflection
  warnings.warn(msg)
```
However, for sqlite it throws an error:
```shell
Traceback (most recent call last):
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/bin/alembic", line 11, in <module>
    load_entry_point('alembic==1.0.5', 'console_scripts', 'alembic')()
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/config.py", line 503, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/config.py", line 497, in main
    self.run_cmd(cfg, options)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/config.py", line 480, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/command.py", line 176, in revision
    script_directory.run_env()
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/util/compat.py", line 145, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 71, in <module>
    run_migrations_online()
  File "alembic/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/command.py", line 156, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/api.py", line 415, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/api.py", line 451, in _run_environment
    autogen_context, migration_script)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 22, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 48, in _produce_net_changes
    autogen_context, upgrade_ops, schemas
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/util/langhelpers.py", line 315, in go
    fn(*arg, **kw)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 75, in _autogen_for_tables
    inspector, upgrade_ops, autogen_context)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 190, in _compare_tables
    s, tname, conn_table, metadata_table
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/util/langhelpers.py", line 315, in go
    fn(*arg, **kw)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 427, in _compare_indexes_and_uniques
    conn_indexes = set(_make_index(ix, conn_table) for ix in conn_indexes)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 427, in <genexpr>
    conn_indexes = set(_make_index(ix, conn_table) for ix in conn_indexes)
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 200, in _make_index
    *[conn_table.c[cname] for cname in params['column_names']],
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/alembic/autogenerate/compare.py", line 200, in <listcomp>
    *[conn_table.c[cname] for cname in params['column_names']],
  File "/Users/krystofpilnacekrossum/workspace/elis-connector-integreon/venv/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: None
```

In the end, it's not that big deal as it is possible to generate the migration using postgres and apply it on SQLite.

**Comment by zzzeek** [comment]
mmmm I'm not reproducing a problem here on this end, and it's a little unclear what exactly you're doing.   you're saying, you define the model as follows, then run autogenerate, but that means the functional index is *not* in the database, yet you are getting a PG reflection warning.  It's not possible to get this warning on SQLite because SQLite doesn't have functional indexes.  So I dont undersrtand what you are doing.

can you provide:

1. SQLAlchemy version in use

2. *exact* sequence of steps to reproduce, starting from a blank database

3. if you can clarify what the state of the database is before the error, in the PG case it seems you have existing schema elements, then also, what's in the SQLite database then?

2. does this reproduce from scratch on a blank SQLite database and this is the first revision?  or does there need to be a table already present and you are adding the index after the fact?  (I've tried it both ways and neither produces the issue) ?

**Comment by KPilnacek** [comment]
Oh, sorry for being unclear. The state DB before running the autogenerate is as described (see details below)

1. SQLAlchemy 1.2.15
2. I'll try to put together a MWE throughout the day but for now, the steps should be:
    1. run `alembic revision --autogenerate` (this should be OK)
    2. run `alembic upgrade head` (this should be OK as well -- produces the state described below)
    3. run `alembic revision --autogenerate` (this should throw the error)
3. The database is upgraded to the state stated:
Postgres:
```
database=# \d
              List of relations
 Schema |      Name       |   Type   | Owner 
--------+-----------------+----------+-------
 public | alembic_version | table    | elis
 public | suppliers       | table    | elis
(2 rows)

database=# \d suppliers
                    Table "public.suppliers"
 Column |         Type          | Collation | Nullable | Default 
--------+-----------------------+-----------+----------+---------
 id     | character varying(20) |           | not null | 
 name   | character varying     |           |          | 
Indexes:
    "suppliers_pkey" PRIMARY KEY, btree (id)
    "ix_suppliers_name" btree (name)
    "supplier_name_idx" btree (replace(replace(replace(lower(name::text), '.'::text, ''::text), ' '::text, ''::text), ','::text, ''::text))

```
SQLite:
```sql
sqlite> .schema
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
CREATE TABLE suppliers (
	id VARCHAR(20) NOT NULL, 
	name VARCHAR, PRIMARY KEY (id)
);
CREATE INDEX ix_suppliers_name ON suppliers (name);
CREATE INDEX supplier_name_idx ON suppliers (replace(replace(replace(lower(name), '.', ''), ' ', ''), ',', ''));
```
4. Before the `alembic revision --autogenerate` there was both the table and the index (as described in 2. and 3.).

P.S. I didn't know about SQLite not having functional indices (though should have assume it 🤦‍♂️ ). That makes this issue even less important.

Though I can imagine a use-case where there is SQLite DB for testing and Postgres (or any other less Lite DB) for production or a case where you start small (with SQLite) and as you grow you assume switching to Postgres and you do not want to forget about the functional index.

**Comment by zzzeek** [comment]
> P.S. I didn't know about SQLite not having functional indices 

sorry I was mistaken in my wording.  SQLAlchemy's SQLite dialect does not detect these indexes, is what goes on. given your DDL, If I reflect it back I get the warning:

/home/classic/dev/sqlalchemy/lib/sqlalchemy/engine/reflection.py:891: SAWarning: index key 'None' was not located in columns for table 'suppliers'
  "columns for table '%s'" % (flavor, c, table_name)

so I think it is skipping the knowledge of that index entirely.

**Comment by zzzeek** [comment]
so yes that reproduces your stack trace as well, so this is more a SQLAlchemy bug for the moment where Alembic will need a workaround

**Comment by zzzeek** [comment]
I'm leaning towards not merging this because the fix is going to be ready for SQLAlchemy 1.2.16 in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1085/

**Comment by zzzeek** [comment]
ha, older SQLite's (like the one running on my centos servers) *dont* support functional indexes, so I wasn't crazy:

OperationalError: (sqlite3.OperationalError) near "(": syntax error [SQL: "\n                CREATE INDEX idx2 ON exp_index (\n                replace(replace(replace(lower(name), '.', ''), ' ', '')\n                , ',', ''));\n            "] (

**Comment by zzzeek** [comment]
sqlite 3.9.0: https://sqlite.org/expridx.html
