### ISSUE TITLE
flask db migrate Fails: Raise TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by HarshadKavathiya** [sqlalchemy/alembic#533]
I am using Python 2.7.15 and MySQL 8.0.13 on Mac OS X 10.14.2 and using the Following package:

Flask==1.0.2

Flask-Migrate==2.3.1,

PyMySQL==0.9.3,

Flask-SQLAlchemy==2.3.2,

SQLAlchemy==1.2.16,

alembic==1.0.7

When I run "**flask db init**", "**flask db migrate**" & "**flask db upgrade**" on the empty/clean database, it runs without any issue and create table according to model file.

**Please note that i am facing this issue second time and onward.**
After that whenever I try "**flask db migrate**" command I am getting an error as follows:

```
(venv) MACSYSTEM-2:flask_project account$ flask db migrate
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.env] descriptor 'lower' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/Users/account/PycharmProjects/flask_project/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/command.py", line 197, in revision
    script_directory.run_env()
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 90, in <module>
    run_migrations_online()
  File "migrations/env.py", line 83, in run_migrations_online
    raise exception
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

```

Please guide me how I can solve this issue.

**Comment by mikeywaites** [comment]
Hi @HarshadKavathiya 

Sorry for the slow reply.  Can you provide me with some more information.  Ideally your models, migrations directory including env.py, your alembic.ini.  The more you can give me the more i'll be able to help.

**Comment by HarshadKavathiya** [comment]
@mikeywaites thank you for the response.  
I am facing this issue with Python 2 only, when I used python 3.6.5 and used the same code & requirements.txt, I am not getting said error. Seems like it is related to python 2 bug.

**Comment by HarshadKavathiya** [comment]
**==> alembic.ini**
```
# A generic, single database configuration.

[alembic]
# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

```

**==> env.py**

```
from __future__ import with_statement
from alembic import context
from sqlalchemy import engine_from_config, pool
from logging.config import fileConfig
import logging

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
fileConfig(config.config_file_name)
logger = logging.getLogger('alembic.env')

# add your model's MetaData object here
# for 'autogenerate' support
# from myapp import mymodel
# target_metadata = mymodel.Base.metadata
from flask import current_app
config.set_main_option('sqlalchemy.url',
                       current_app.config.get('SQLALCHEMY_DATABASE_URI'))
target_metadata = current_app.extensions['migrate'].db.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url)

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    # this callback is used to prevent an auto-migration from being generated
    # when there are no changes to the schema
    # reference: http://alembic.zzzcomputing.com/en/latest/cookbook.html
    def process_revision_directives(context, revision, directives):
        if getattr(config.cmd_opts, 'autogenerate', False):
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                logger.info('No changes in schema detected.')

    engine = engine_from_config(config.get_section(config.config_ini_section),
                                prefix='sqlalchemy.',
                                poolclass=pool.NullPool)

    connection = engine.connect()
    context.configure(connection=connection,
                      target_metadata=target_metadata,
                      process_revision_directives=process_revision_directives,
                      **current_app.extensions['migrate'].configure_args)
    
    try:
        with context.begin_transaction():
            context.run_migrations()
    except Exception as exception:
        logger.error(exception)
        raise exception
    finally:
        connection.close()

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
```

**==> script.py.mako:**
```
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}

```

**Comment by zzzeek** [comment]
can you please correct your exception logging to look like this:

```
    try:
        with context.begin_transaction():
            context.run_migrations()
    except Exception:
        logger.error("error", exc_info=True)
        raise
    finally:
        connection.close()
```

then report on the full stack trace from the real source of the exception.  additionally please indicate if the word "lower()" appears in one of your migration scripts, or anywhere in the process.

**Comment by HarshadKavathiya** [comment]
Hi @zzzeek,

As you suggest I update env.py file and now this is execution log. Please have a look. Also, I would like to confirm that I am not using "lower()" keyword in any of my migration scripts or models scripts. Seems like exception raised by "/sqlalchemy/dialects/mysql/base.py: line 2484". I hope this information will help you. 

```
(venv) 192:flask_project account$ flask db migrate
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.env] descriptor 'lower' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/Users/account/PycharmProjects/flask_project/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/command.py", line 197, in revision
    script_directory.run_env()
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 90, in <module>
    run_migrations_online()
  File "migrations/env.py", line 83, in run_migrations_online
    raise exception
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
(venv) 192:flask_project account$ flask db migrate
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.env] error
Traceback (most recent call last):
  File "migrations/env.py", line 84, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/runtime/migration.py", line 350, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/command.py", line 173, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 433, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 473, in _run_environment
    autogen_context, migration_script
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 25, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 51, in _produce_net_changes
    autogen_context, upgrade_ops, schemas
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/langhelpers.py", line 320, in go
    fn(*arg, **kw)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 83, in _autogen_for_tables
    autogen_context,
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 195, in _compare_tables
    inspector.reflecttable(t, None)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 652, in reflecttable
    reflection_options,
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 785, in _reflect_fk
    table_name, schema, **table.dialect_kwargs
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 452, in get_foreign_keys
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_foreign_keys
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2454, in get_foreign_keys
    self._correct_for_mysql_bug_88718(fkeys, connection)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2484, in _correct_for_mysql_bug_88718
    for col_name in rec["referred_columns"]
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/Users/account/PycharmProjects/flask_project/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/cli.py", line 90, in migrate
    rev_id, x_arg)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/flask_migrate/__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/command.py", line 197, in revision
    script_directory.run_env()
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/compat.py", line 216, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 95, in <module>
    run_migrations_online()
  File "migrations/env.py", line 84, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/runtime/migration.py", line 350, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/command.py", line 173, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 433, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/api.py", line 473, in _run_environment
    autogen_context, migration_script
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 25, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 51, in _produce_net_changes
    autogen_context, upgrade_ops, schemas
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/util/langhelpers.py", line 320, in go
    fn(*arg, **kw)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 83, in _autogen_for_tables
    autogen_context,
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/alembic/autogenerate/compare.py", line 195, in _compare_tables
    inspector.reflecttable(t, None)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 652, in reflecttable
    reflection_options,
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 785, in _reflect_fk
    table_name, schema, **table.dialect_kwargs
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 452, in get_foreign_keys
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_foreign_keys
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2454, in get_foreign_keys
    self._correct_for_mysql_bug_88718(fkeys, connection)
  File "/Users/account/PycharmProjects/flask_project/venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2484, in _correct_for_mysql_bug_88718
    for col_name in rec["referred_columns"]
TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

```

**Comment by zzzeek** [comment]
fixed in https://github.com/sqlalchemy/sqlalchemy/issues/4492
