### ISSUE TITLE
mysql 8.0.16 CHECK constraint add not supporting col renames like mariadb did

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#556]
```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1054, "Unknown column 'flag' in 'check constraint bar_chk_1 expression'") [SQL: ALTER TABLE bar CHANGE flag bflag BOOL NULL] (Background on this error at: http://sqlalche.me/e/e3q8)

Traceback (most recent call last):
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/tests/test_batch.py", line 1643, in test_rename_column_boolean
    super(BatchRoundTripMySQLTest, self).test_rename_column_boolean()
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/tests/test_batch.py", line 1470, in test_rename_column_boolean
    "flag", new_column_name="bflag", existing_type=Boolean
  File "/opt/python3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/alembic/operations/base.py", line 325, in batch_alter_table
    impl.flush()
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/alembic/operations/batch.py", line 73, in flush
    fn(*arg, **kw)
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/alembic/ddl/mysql.py", line 64, in alter_column
    else existing_autoincrement,
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/home/jenkins/workspace/alembic_gerrit/1d95c17e/.tox/py37-sqlamaster-sqlite-postgresql-mysql-oracle/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute

```

we need to update the _mariadb_only_102 logic to include both DBs

**Comment by zzzeek** [comment]
additionally MariaDB 10.2.22 seems to be passing so try to add that as well

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Tune "rename boolean column w CHECK constraint" test for MySQL 8, mariadb10.2** https://gerrit.sqlalchemy.org/1246
