### ISSUE TITLE
migration message does not support non ascii characters

### ISSUE THREAD

**Issue by lohxx** [sqlalchemy/alembic#584]
When i try to create a migration that contains a non ascii characters in the message, the migration fail.

```python


Traceback (most recent call last):
  File "/home/lohanna/digesto/op/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 14, in template_to_file
    output = template.render_unicode(**kw).encode(output_encoding)
  File "/home/lohanna/digesto/op/venv/local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/home/lohanna/digesto/op/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/lohanna/digesto/op/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/lohanna/digesto/op/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "alembic/script.py.mako", line 1, in render_body
    """${message}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 29: ordinal not in range(128)


```

**Comment by zzzeek** [comment]
this only applies to Python 2 which is EOL in six months.   For Python 2, you have to modify script.py.mako to accommodate both for a bytes message as well as a Python source file that will use a particular encoding, such as utf-8:

```
<%text># coding: utf-8</%text>
"""${message.decode("utf-8")}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}

```

**Comment by zzzeek** [comment]
here's an approach that works on both python 2 and 3:

```
<%!
	import sys
%>
<%text># coding: utf-8</%text>
"""${message.decode("utf-8") if sys.version_info < (3, ) and isinstance(message, str) else message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}

```

I'm hesitant to add this to Alembic beacuse there could be non-ascii in the other parts of the template, there's the encoding comment, all of which would have to be configured by a bunch of options that I'd have to document only for them to all go away for Python 3 only.

**Comment by zzzeek** [comment]
however I am adding the above to the docs so problem solved.
