### ISSUE TITLE
Adding a unique constraint doesn't work when more than one columns are given.

### ISSUE THREAD

**Issue by Nikitas-io** [sqlalchemy/alembic#595]
So I tried adding a unique constraint for two columns of a table at the same time and migrating to it. This works if I drop the database and create the new one using these changes but I cannot migrate to the new database version using alembic.

Here's the class I want to add the constraint to:
```
class UserItems(BASE):
    __tablename__ = 'user_items'
    id = Column(Integer, primary_key=True)

    user_id = Column(Integer, ForeignKey('users.id'))
    user = relationship('Users', back_populates='items')

    item_id = Column(Integer, ForeignKey('items.id'), nullable=False)
    item= relationship('Items', back_populates='users')

    # The combination of a user and an item should be unique.
    __table_args__ = (UniqueConstraint('user_id', 'item_id',
                                       name='unique_association'), )
```

And here's the code that is supposed to upgrade the database:
```
def upgrade():
    with op.batch_alter_table("user_items") as batch_op:
        batch_op.create_unique_constraint("unique_association", "user_items", ["user_id', 'item_id"])
```

When I run the `python3 migrate.py db upgrade` command, I get this error:
```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 740399c84e0f, empty message
Traceback (most recent call last):
  File "migrate.py", line 13, in <module>
    manager.run()
  File "/usr/local/lib/python3.5/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.5/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.5/dist-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.5/dist-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.5/dist-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.5/dist-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 96, in <module>
    run_migrations_online()
  File "migrations/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.5/dist-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.5/dist-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/vagrant/Project/migrations/versions/740399c84e0f_.py", line 26, in upgrade
    ["user_id", "item_id"])
TypeError: <flask_script.commands.Command object at 0x7fe108a46fd0>: create_unique_constraint() takes 3 positional arguments but 4 were given
```

**Comment by zzzeek** [comment]
hi -

are you using batch migrations because you are targeting SQLite ?

the error is caused because batch_op.create_unique_constraint does not need the table name to be provided:

https://alembic.sqlalchemy.org/en/latest/ops.html?highlight=batchoperations#alembic.operations.BatchOperations.create_unique_constraint

```
def upgrade():
    with op.batch_alter_table("user_items") as batch_op:
        batch_op.create_unique_constraint("unique_association", ["user_id', 'item_id"])

```

however I'm not sure if you typed that by hand, or autogenerate is doing it, or what, feel free to provide more detail

**Comment by Nikitas-io** [comment]
@zzzeek I wrote this code by hand and I'm using postgresql. I am aware that it is not necessary to use batch migrations for this specific case but the original code I was using had a couple more operations of this type. I removed them to simplify my question.

**Comment by zzzeek** [comment]
OK, so , just dont include the table name with the batch version and it should work.

**Comment by zzzeek** [comment]
closing this.
