### ISSUE TITLE
Unable to specify relative revision in command.downgrade API

### ISSUE THREAD

**Issue by babaMar** [sqlalchemy/alembic#603]
I'd like to execute a single downgrade (to previous revision) programmatically, so mimicking the command line functionality I did:

```python
alembic_cfg = Config(os.path.join(APP_ROOT, 'alembic.ini'))        
command.downgrade(alembic_cfg, '-1')
```

Unfortunately it is not going through as expected:
```python
Traceback (most recent call last):                                                                                                                
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors                                       
    yield                                                                                                                                         
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 348, in _downgrade_revs                                              
    current_rev, destination, select_for_downgrade=True)                                                                                          
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 556, in iterate_revisions                                        
    inclusive, assert_relative_length                                                                                                             
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 528, in _relative_iterate                                        
    "produce %d migrations" % (destination, abs(relative)))                                                                                       
alembic.script.revision.RevisionError: Relative revision -1 didn't produce 1 migrations 
```

anything am I doing wrong or it's just not supported?

**Comment by zzzeek** [comment]
it's likely trying to move over a merge or branchpoint ?  if this were a straight line of migrations, it should work.   can you clarify the migration structure?

**Comment by zzzeek** [comment]
potentialy related to #464

**Comment by zzzeek** [comment]
oh, also, can you clarify, if you are saying that this downgrade is failing only programatically and not when you do the command line?  that would be a different issue.

**Comment by zzzeek** [comment]
additionally this error is raised if there are no further downgrade migrations to run.

**Comment by zzzeek** [comment]
no activity, can't reproduce

**Comment by sqla-tester** [comment]
**Simon Bowly** has proposed a fix for this issue in the **master** branch:

**New downgrade algorithm to fix branch behaviour** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2530
