### ISSUE TITLE
Allow to run statement before creating `alembic_version` table in Postgres

### ISSUE THREAD

**Issue by notrev** [sqlalchemy/alembic#611]
I need to run `SET ROLE writer_role;` before creating a table in Postgres, because the user role I use to login does not have `CREATE` permission in the schema. And it is not possible to login with `writer_role`.

This causes the auto generation of the initial revision (`alembic revision --autogenerate -m "initial") to fail when it tries to create the `alembic_version` table and it does not generate the initial migration file.

The output of the command mentioned above is:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: permission denied for schema public
LINE 2: CREATE TABLE alembic_version (
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 573, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 567, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 547, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.6/dist-packages/alembic/command.py", line 214, in revision
    script_directory.run_env()
  File "/usr/local/lib/python3.6/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/compat.py", line 173, in load_module_py                                                                                                                                         spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 89, in <module>
    run_migrations_online()
  File "alembic/env.py", line 83, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/migration.py", line 499, in run_migrations
    self._ensure_version_table()
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/migration.py", line 440, in _ensure_version_table
    self._version.create(self.connection, checkfirst=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/schema.py", line 870, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1615, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) permission denied for schema public
LINE 2: CREATE TABLE alembic_version (
                     ^

[SQL:
CREATE TABLE alembic_version (
        version_num VARCHAR(32) NOT NULL,
        CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by zzzeek** [comment]
there's nothing Alembic can do here, when you first do CREATE DATABASE you need to also create the proper roles for the user which administrating the database.

**Comment by zzzeek** [comment]
if you are doing things with autogenerate, which necesarily works against a live database that is assumed to be versioned, you should use a development database.   sqlite can work just to create your initial migrations

**Comment by notrev** [comment]
Thanks for the information, @zzzeek . I have decided to go with the offline mode, it works well with the setup we have.

**Comment by JockeTF** [comment]
You may be able to sneak in `connection.execute("SET ROLE 'writer_role'")` right before passing the connection to `context.configure()` in `env.py`.

**Comment by reaper993** [comment]
Hi, this may be late. 
You could login to your database as the owner(postgres) user:` \c <batabase name> postgres`
and execute: `GRANT ALL ON SCHEMA public TO <your database user>;`
This should give access to your database user to create table on public schema. Now you can go back and execute `alembic revision --autogenerate -m "initial"` and verify.
Hope this helps.

**Comment by psudocoder1123** [comment]
I am using below mentioned function to grant access to user `trend_calculator` :
```
def upgrade():
    op.execute("GRANT ALL ON ALL TABLES IN SCHEMA public TO trend_calculator;")
```
But this fails with error, according to this this expectes role to be passed instead of user , I also passes User as a prefix but was getting the same error :

```
sqlalchemy.exc.ProgrammingError: (pg8000.dbapi.ProgrammingError) {'S': 'ERROR', 'V': 'ERROR', 'C': '42704', 'M': 'role "trend_calculator" does not exist', 'F': 'acl.c', 'L': '5101', 'R': 'get_role_oid'}
[SQL: GRANT ALL ON ALL TABLES IN SCHEMA public TO trend_calculator;]
(Background on this error at: https://sqlalche.me/e/20/f405)

```

**Comment by CaselIT** [comment]
the error seems to be `role "trend_calculator" does not exist`.
I'm not sure how it's related to this closed issue
