### ISSUE TITLE
SQLAlchemy has added support for computed col reflection; need to adapt Alembic tests

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#669]
e.g.

Traceback (most recent call last):
  File "/home/jenkins/workspace/alembic_master/00816f09/tests/test_autogen_computed.py", line 65, in test_remove_computed_column
    is_(c.computed, None)
  File "/home/jenkins/workspace/alembic_master/00816f09/.tox/py38-sqla13-sqlite-postgresql-mysql-oracle/lib/python3.8/site-packages/sqlalchemy/testing/assertions.py", line 264, in is_
    assert a is b, msg or "%r is not %r" % (a, b)
AssertionError: Computed(<sqlalchemy.sql.elements.TextClause object at 0x7fb51dc02280>, persisted=False) is not None
assert Computed(<sqlalchemy.sql.elements.TextClause object at 0x7fb51dc02280>, persisted=False) is None

**Comment by zzzeek** [comment]
basically the tests and maybe the compare module need to be sensitive to the version of SQLAlchemy in use and adjust accordingly

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support computed reflection.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1797
