### ISSUE TITLE
AttributeError on CLI commands for Python 3.7.7

### ISSUE THREAD

**Issue by huangsam** [sqlalchemy/alembic#673]
I encountered the following issue when running `alembic upgrade head` / `alembic current`:

```
Traceback (most recent call last):
  File ".../venv/bin/alembic", line 11, in <module>
    sys.exit(main())
  File ".../venv/lib/python3.7/site-packages/alembic/config.py", line 575, in main
    CommandLine(prog=prog).main(argv=argv)
  File ".../venv/lib/python3.7/site-packages/alembic/config.py", line 569, in main
    self.run_cmd(cfg, options)
  File ".../venv/lib/python3.7/site-packages/alembic/config.py", line 549, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File ".../venv/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File ".../venv/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File ".../venv/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File ".../venv/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/.../scripts/migrations/env.py", line 101, in <module>
    run_migrations_online()
  File "src/.../scripts/migrations/env.py", line 84, in run_migrations_online
    alembic_config, prefix="sqlalchemy.", poolclass=pool.NullPool
  File ".../venv/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 522, in engine_from_config
    return create_engine(url, **options)
  File ".../venv/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File ".../venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    plugins = u._instantiate_plugins(kwargs)
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'
```

Environment:

- Python 3.7.7
- Mac OS Catalina
- SQLAlchemy 1.3.13
- alembic 1.3.3

**Comment by zzzeek** [comment]
alembic is at 1.4.2 right now so upgrading is the first thing to do, also make sure your python environment is cleanly installed, that there are no remnants of older versions of SQLAlchemy or Alembic lying around.  if you are using a virutal environment, try creating it fresh.

**Comment by huangsam** [comment]
Turns out that I didn't configure the database URL in the alembic migration script. Once that got fixed, no issues came up. Simple user error!
