### ISSUE TITLE
Can't use unicode in script.py.mako

### ISSUE THREAD

**Issue by retnikt** [sqlalchemy/alembic#701]
**Describe the bug**
When creating a revision where the `script.py.mako` file contains unicode characters that are not decodeable with ASCII, an exception is produced

**Expected behavior**
The unicode characters are copied correctly into the generated revision file.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

`script.py.mako`:
```mako
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
Some unicode here: © ê 😎
"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}

def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}

```
then run
```sh
alembic revision -m "foobar"
```

**Error**

```pytb
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
  Generating ...alembic/versions/90c07ba1d524_foobar.py ...  FAILED
Traceback (most recent call last):
  File "...python3.8/site-packages/mako/lexer.py", line 229, in decode_raw_stream
    text = text.decode(parsed_encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 118: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...bin/alembic", line 8, in <module>
    sys.exit(main())
  File "...python3.8/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "...python3.8/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "...python3.8/site-packages/alembic/config.py", line 548, in run_cmd
    fn(
  File "...python3.8/site-packages/alembic/command.py", line 221, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "...python3.8/site-packages/alembic/command.py", line 221, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "...python3.8/site-packages/alembic/autogenerate/api.py", line 513, in generate_scripts
    yield self._to_script(generated_revision)
  File "...python3.8/site-packages/alembic/autogenerate/api.py", line 429, in _to_script
    return self.script_directory.generate_revision(
  File "...python3.8/site-packages/alembic/script/base.py", line 640, in generate_revision
    self._generate_template(
  File "...python3.8/site-packages/alembic/script/base.py", line 496, in _generate_template
    util.status(
  File "...python3.8/site-packages/alembic/util/messaging.py", line 52, in status
    ret = fn(*arg, **kw)
  File "...python3.8/site-packages/alembic/util/pyfiles.py", line 17, in template_to_file
    template = Template(filename=template_file)
  File "...python3.8/site-packages/mako/template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "...python3.8/site-packages/mako/template.py", line 430, in _compile_from_file
    code, module = _compile_text(self, data, filename)
  File "...python3.8/site-packages/mako/template.py", line 733, in _compile_text
    source, lexer = _compile(
  File "...python3.8/site-packages/mako/template.py", line 712, in _compile
    node = lexer.parse()
  File "...python3.8/site-packages/mako/lexer.py", line 243, in parse
    self.encoding, self.text = self.decode_raw_stream(
  File "...python3.8/site-packages/mako/lexer.py", line 231, in decode_raw_stream
    raise exceptions.CompileException(
mako.exceptions.CompileException: Unicode decode operation of encoding 'ascii' failed in file 'alembic/script.py.mako' at line: 0 char: 0
```

**Versions.**
 - OS: Linux
 - Python: 3.8.3
 - Alembic: 1.4.2
 - SQLAlchemy: 1.3.17
 - Database: PostgreSQL 12
 - DBAPI: psycopg2 2.8.5

**Additional context**
It seems you need to pass `input_encoding='utf-8'` and `output_encoding='utf-8'` when loading the template. ([source](https://stackoverflow.com/questions/4497515/unicodeencodeerror-in-mako-template))

**Have a nice day!**

**Comment by zzzeek** [comment]
that stackoverflow answer refers to data in the template that's not ascii, and that should not apply in Python 3.   the template itself needs an encoding comment, simply add this at the top of script.py.mako:

   #! coding: utf-8

**Comment by zzzeek** [comment]
this is #267 in mako will be released shortly
