### ISSUE TITLE
Use alembic  to drop table column of sqlite failed.

### ISSUE THREAD

**Issue by Arvin-He** [sqlalchemy/alembic#737]
**Describe the bug**

In a table model, I want to remove hash column, like this

```python
class Posts(BaseModel):
    __tablename__ = 'posts'
    id = Column(Integer, primary_key=True)
    title = Column(String(64), default='')
    content = Column(Text, default='')
    category = Column(String(32), default='')
    keywords = Column(String(32), default='')
    read = Column(Integer, default=0)
    draft = Column(Integer, default=0)
    visible = Column(Integer, default=1)
    create_time = Column(Integer, default=int(time.time()))
    update_time = Column(Integer, default=int(time.time()))
    # hash = Column(String(64), default='')
```

when I modify the posts model, 
then I exec command:  `alembic revision --autogenerate -m "remove hash"`,  
it works sucessfully, results see below.

```bash
alembic revision --autogenerate -m "remove hash"
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected removed column 'posts.hash'
Generating C:\workspace\fjblogs\tornadoserver\migratedb\versions\7cc1a1c716eb_remove_hash.py ...  done
```

then I exec command: `alembic upgrade head`, it failed. error see below.

```bash
alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c8b2c89ed412 -> 7cc1a1c716eb, remove hash
Traceback (most recent call last):
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DROP": syntax error
...
```

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
 alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c8b2c89ed412 -> 6d50303f7cd0, remove hash
Traceback (most recent call last):
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DROP": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\programs\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programs\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\programs\python38\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "c:\programs\python38\lib\site-packages\alembic\config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "c:\programs\python38\lib\site-packages\alembic\config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "c:\programs\python38\lib\site-packages\alembic\config.py", line 552, in run_cmd
    fn(
  File "c:\programs\python38\lib\site-packages\alembic\command.py", line 298, in upgrade
    script.run_env()
  File "c:\programs\python38\lib\site-packages\alembic\script\base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\programs\python38\lib\site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\programs\python38\lib\site-packages\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migratedb\env.py", line 87, in <module>
    run_migrations_online()
  File "migratedb\env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "c:\programs\python38\lib\site-packages\alembic\runtime\environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "c:\programs\python38\lib\site-packages\alembic\runtime\migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "C:\workspace\fjblogs\tornadoserver\migratedb\versions\6d50303f7cd0_remove_hash.py", line 21, in upgrade
    op.drop_column('posts', 'hash')
  File "<string>", line 8, in drop_column
  File "<string>", line 3, in drop_column
  File "c:\programs\python38\lib\site-packages\alembic\operations\ops.py", line 2049, in drop_column
    return operations.invoke(op)
  File "c:\programs\python38\lib\site-packages\alembic\operations\base.py", line 373, in invoke
    return fn(self, operation)
  File "c:\programs\python38\lib\site-packages\alembic\operations\toimpl.py", line 80, in drop_column
    operations.impl.drop_column(
  File "c:\programs\python38\lib\site-packages\alembic\ddl\impl.py", line 241, in drop_column
    self._exec(base.DropColumn(table_name, column, schema=schema))
  File "c:\programs\python38\lib\site-packages\alembic\ddl\impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "c:\programs\python38\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DROP": syntax error
[SQL: ALTER TABLE posts DROP COLUMN hash]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
jun.he@JS-E-PC-10147 /c/workspace/fjblogs/tornadoserver (master)
λ alembic revision --autogenerate -m "remove hash"
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected removed column 'posts.hash'
Generating C:\workspace\fjblogs\tornadoserver\migratedb\versions\7cc1a1c716eb_remove_hash.py ...  done
jun.he@JS-E-PC-10147 /c/workspace/fjblogs/tornadoserver (master)
λ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c8b2c89ed412 -> 7cc1a1c716eb, remove hash
Traceback (most recent call last):
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DROP": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\programs\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programs\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\programs\python38\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "c:\programs\python38\lib\site-packages\alembic\config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "c:\programs\python38\lib\site-packages\alembic\config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "c:\programs\python38\lib\site-packages\alembic\config.py", line 552, in run_cmd
    fn(
  File "c:\programs\python38\lib\site-packages\alembic\command.py", line 298, in upgrade
    script.run_env()
  File "c:\programs\python38\lib\site-packages\alembic\script\base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\programs\python38\lib\site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\programs\python38\lib\site-packages\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migratedb\env.py", line 87, in <module>
    run_migrations_online()
  File "migratedb\env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "c:\programs\python38\lib\site-packages\alembic\runtime\environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "c:\programs\python38\lib\site-packages\alembic\runtime\migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "C:\workspace\fjblogs\tornadoserver\migratedb\versions\7cc1a1c716eb_remove_hash.py", line 21, in upgrade
    op.drop_column('posts', 'hash')
  File "<string>", line 8, in drop_column
  File "<string>", line 3, in drop_column
  File "c:\programs\python38\lib\site-packages\alembic\operations\ops.py", line 2049, in drop_column
    return operations.invoke(op)
  File "c:\programs\python38\lib\site-packages\alembic\operations\base.py", line 373, in invoke
    return fn(self, operation)
  File "c:\programs\python38\lib\site-packages\alembic\operations\toimpl.py", line 80, in drop_column
    operations.impl.drop_column(
  File "c:\programs\python38\lib\site-packages\alembic\ddl\impl.py", line 241, in drop_column
    self._exec(base.DropColumn(table_name, column, schema=schema))
  File "c:\programs\python38\lib\site-packages\alembic\ddl\impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "c:\programs\python38\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\programs\python38\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DROP": syntax error
[SQL: ALTER TABLE posts DROP COLUMN hash]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Versions.**
 - OS: win10
 - Python: 3.8.2
 - Alembic: 1.4.3
 - SQLAlchemy: 1.3.19
 - Database: sqlite3
 - DBAPI: 

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,
Could you also share the generated alembic file?

**Comment by Arvin-He** [comment]
the generated alembic file:  `de260b2ad766_remove_hash.py`

```py
"""remove hash

Revision ID: de260b2ad766
Revises: c8b2c89ed412
Create Date: 2020-09-17 15:33:44.609597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de260b2ad766'
down_revision = 'c8b2c89ed412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hash', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###

```

**Comment by CaselIT** [comment]
I think you need to use the batch mode with sqlite to modify a table: https://alembic.sqlalchemy.org/en/latest/batch.html

I'm not sure if autogenerate can automatically render it or if you have to update the file by hand after the autogenerate has run.

**Comment by Arvin-He** [comment]
@CaselIT Thanks! I tried use the batch mode with sqlite to modify a table, it doesn't work, 
but i update the file by hand after the autogenerate command. It works. 

the generated alembic file: 96afca42559c_remove_hash.py

```py
"""remove hash

Revision ID: 96afca42559c
Revises: c8b2c89ed412
Create Date: 2020-09-18 08:59:50.263439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96afca42559c'
down_revision = 'c8b2c89ed412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('posts', 'hash')   # this doesn't work
    # the batch mode to drop column by  hand
    with op.batch_alter_table("posts") as batch_op:
        batch_op.drop_column('hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hash', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###

```
