### ISSUE TITLE
When typing 'alembic upgrade head --sql' for MSSQL connection,  I see 'MockConnection' object has no attribute 'close'

### ISSUE THREAD

**Issue by alexmc-ms** [sqlalchemy/alembic#740]
**Describe the bug**
When typing 'alembic upgrade head --sql' on MSSQL I see 'MockConnection' object has no attribute 'close'

**Expected behavior**
I expect it would show me the SQL that is going to be used to create the tables

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

Because there is a type mismatch in Apache Airflow where the alembic table creation uses VARCHAR for String for MSSQL via ODBC and sqlalchemy uses NVARCHAR for String, I want to get the SQL that is sent to the server so I can replace all VARCHARs with NVARCHARs.  In this way I can ensure the tables are created with the correct type.

This error can be seen without actually running Apache Airflow.

1. Get the Apache Airflow migrations https://github.com/apache/airflow/tree/master/airflow/migrations/versions.
2. alembic init migrations
3. pip3 install apache-airflow, pip3 install pyodbc
4. alembic upgrade head --sql

```py
# alembic.ini
[alembic]
script_location = migrations
sqlalchemy.url = mssql+pyodbc://<login>:<password>@<server>:1433/<database>?driver=ODBC+Driver+17+for+SQL+Server
[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples

# format using "black" - use the console_scripts runner, against the "black" entrypoint
# hooks=black
# black.type=console_scripts
# black.entrypoint=black
# black.options=-l 79

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
```

```py
# env.py
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

import os
import sys
sys.path.append(os.getcwd())

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
fileConfig(config.config_file_name)

from app.db import Base
target_metadata = Base.metadata

def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
```

```py
# db.py
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

engine = create_engine('mssql+pyodbc://<login>:<password>@<server>:1433/<database>?driver=ODBC+Driver+17+for+SQL+Server')

Base = declarative_base()
```

**Error**

```
# Copy error here. Please include the full stack trace.
$ alembic upgrade head --sql
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Generating static SQL
INFO  [alembic.runtime.migration] Will assume transactional DDL.
BEGIN TRANSACTION;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

GO

Running upgrade  -> e3a246e0dc1, current schema
-- Running upgrade  -> e3a246e0dc1

Traceback (most recent call last):
  File "/opt/aristo/airflow/python/bin/alembic", line 11, in <module>
    load_entry_point('alembic==1.4.0', 'console_scripts', 'alembic')()
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/config.py", line 551, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/util/compat.py", line 173, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 81, in <module>
    run_migrations_offline()
  File "migrations/env.py", line 55, in run_migrations_offline
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/home/aristo/ch12/migrations/versions/e3a246e0dc1_current_schema.py", line 42, in upgrade
    inspector = Inspector.from_engine(conn)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 133, in from_engine
    return Inspector(bind)
  File "/opt/aristo/airflow/python/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 107, in __init__
    bind.connect().close()
AttributeError: 'MockConnection' object has no attribute 'close'
```

**Versions.**
 - OS: Linux Debian9 (custom kernel)
 - Python: 3.7.6
 - Alembic: 1.4.0
 - SQLAlchemy: 1.3.13
 - Database: Azure MSSQL Database
 - DBAPI:

**Additional context**

**Have a nice day!**
Any assistance on this would be appreciated.  Thank you.

**Comment by zzzeek** [comment]
hi there -

the issue is that one of your migration scripts is performing an illegal operation for --sql mode:

in "/home/aristo/ch12/migrations/versions/e3a246e0dc1_current_schema.py":

the code is calling:

    inspector = Inspector.from_engine(conn)

you can't do reflection operations in a migration script that wants to produce --sql mode.  

per https://alembic.sqlalchemy.org/en/latest/offline.html#writing-migration-scripts-to-support-script-generation:

> he challenge of SQL script generation is that the scripts we generate can’t rely upon any client/server database access. This means a migration script that pulls some rows into memory via a SELECT statement will not work in --sql mode. It’s also important that the Alembic directives, all of which are designed specifically to work in both “live execution” as well as “offline SQL generation” mode, are used.

hope this helps!

**Comment by alexmc-ms** [comment]
Thank you zzzeek.  This is useful to know. Appreciate your quick response.
