### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by sjosegarcia** [sqlalchemy/alembic#741]
Hello everyone. I am getting am getting the exception above when running `alembic upgrade head`. I am running in a virtual environment.

I tried using the python path defined by `which python`. To ensure its pointed to my virtualenv. 

Then I tried `python alembic upgrade head`. But I still got this error.

```Traceback (most recent call last):
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/config.py", line 552, in run_cmd
    fn(
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/steven/.local/share/virtualenvs/atletico-F_YCPUGi/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 7, in <module>
    from data.mapping import Base
ModuleNotFoundError: No module named 'data'
```

![image](https://user-images.githubusercontent.com/10678907/94277792-0cf67d80-ff18-11ea-9f3c-511258097ce4.png)

This is my `env.py`:

```
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config
from sqlalchemy import pool

from data.mapping import Base
from utils.config import get_settings

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config
# this will overwrite the ini-file sqlalchemy.url path
# with the path given in the config of the main code
config.set_main_option("sqlalchemy.url", get_settings().database_url)
# Interpret the config file for Python logging.
# This line sets up loggers basically.
fileConfig(config.config_file_name)
# add your model's MetaData object here
target_metadata = Base.metadata


# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()

```

**Comment by sjosegarcia** [comment]
We can close this out... My `PYTHONPATH` was missing within my virtualenv.
