### ISSUE TITLE
Alembic is not dropping enums

### ISSUE THREAD

**Issue by gbrennon** [sqlalchemy/alembic#754]
**Describe the bug**

Alembic is not dropping custom types, like enums, from PostgreSQL.

**Expected behavior**

I expected that when running a `downgrade` alembic would remove everything that was created

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

I have an `Enum` field defined on my mapping module for sqlalchemy. When I try to downgrade and then upgrade again alembic cant apply because the enum wasn't dropped.

```py
recommendation_table = Table(
    'recommendation',
    metadata,
....
    Column('priority', Enum(RecommendationPriorities), nullable=False),
    Column('scope', Enum(RecommendationScopes), nullable=False),
    Column('action', Enum(RecommendationActions), nullable=False),
...
)
```

**Error**

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [alembic.util.messaging] Target database is not up to date.
  FAILED: Target database is not up to date.
root@50a8c720ec61:/financial-services-backend# alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5446a21ee32d, dcf26512b28e -> 226a3d2b2885, empty message
INFO  [alembic.runtime.migration] Running upgrade 226a3d2b2885, 3ecc730f6ead -> 92d29854a53d, empty message
INFO  [alembic.runtime.migration] Running upgrade 92d29854a53d -> 4b5cc957604a, create_financial_plan_and_recommendation
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateObject: type "recommendationpriorities" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 552, in run_cmd
    fn(
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 89, in <module>
    run_migrations_online()
  File "alembic/env.py", line 83, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/financial-services-backend/planners/infrastructure/migrations/4b5cc957604a_create_financial_plan_and_recommendation.py", line 33, in upgrade
    op.create_table('recommendation',
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/ops.py", line 1252, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 256, in create_table
    table.dispatch.before_create(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 645, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1151, in _on_table_create
    t._on_table_create(target, bind, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1565, in _on_table_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1508, in create
    bind.execute(CreateEnumType(self))
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) type "recommendationpriorities" already exists

[SQL: CREATE TYPE recommendationpriorities AS ENUM ('VITAL', 'IMPORTANT', 'NICE_TO_HAVE', 'LOW')]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: Linux 50a8c720ec61 5.8.16-200.fc32.x86_64 #1 SMP Mon Oct 19 14:17:16 UTC 2020 x86_64 GNU/Linux
 - Python: Python 3.8.1
 - Alembic: 1.4.3
 - SQLAlchemy: 1.3.19
 - Database: Postgresql latest
 - DBAPI: idk

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hi -

this is all #278, alembic autogenerate doesn't do PostgreSQL enums right now, you'll have to handle these manually.

**Comment by Mastermind-U** [comment]
Its still not supported, so added custom row to a migration dropdown `op.execute(sa.text('DROP TYPE myenum'))`, works well.
