### ISSUE TITLE
MySQL op.create_index() generates invalid SQL for descending index

### ISSUE THREAD

**Issue by mikhailantoshkin** [sqlalchemy/alembic#772]
**Describe the bug**
When creating a descending index with op.create_index and sa.text in columns arg it generates invalid SQL statement such as 
```SQL
CREATE UNIQUE INDEX ix_created_at ON test ((created_at desc))
```

**Expected behavior**
The generated SQL statement is correct

**To Reproduce**
I'm able to reproduce the problem reliably with this migration
```py
"""test

Revision ID: aeeacd6ac99d
Create Date: 2020-12-26 11:13:02.177139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeeacd6ac99d'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('test',
                    sa.Column('id', sa.Integer, nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_created_at', 'test', [sa.text('created_at desc')], unique=True)


def downgrade():
    pass

```

**Error**

```
{"level":"ERROR","time":"2020-12-26T11:15:43.983672+05:00","process":1,"thread":"MainThread","function":"run_db_migrations","line_no":31,"module":"utils","msg":"(MySQLdb._exceptions.ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc))' at line 1\")\n[SQL: CREATE UNIQUE INDEX ix_created_at ON test ((created_at desc))]\n(Background on this error at: http://sqlalche.me/e/13/f405)","exc_info":"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 593, in do_execute\n    cursor.execute(statement, parameters)\n  File \"/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py\", line 206, in execute\n    res = self._query(query)\n  File \"/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py\", line 319, in _query\n    db.query(q)\n  File \"/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py\", line 259, in query\n    _mysql.connection.query(self, query)\nMySQLdb._exceptions.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc))' at line 1\")\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/app/share/db/migrations/utils.py\", line 29, in run_db_migrations\n    command.upgrade(alembic_cfg, \"head\")\n  File \"/usr/local/lib/python3.8/site-packages/alembic/command.py\", line 298, in upgrade\n    script.run_env()\n  File \"/usr/local/lib/python3.8/site-packages/alembic/script/base.py\", line 489, in run_env\n    util.load_python_file(self.dir, \"env.py\")\n  File \"/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py\", line 98, in load_python_file\n    module = load_module_py(module_id, path)\n  File \"/usr/local/lib/python3.8/site-packages/alembic/util/compat.py\", line 184, in load_module_py\n    spec.loader.exec_module(module)\n  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"data_flows_service/db/migrations/env.py\", line 4, in <module>\n    run_migrations(target_metadata=metadata)\n  File \"/app/share/db/migrations/alembic_env.py\", line 100, in run_migrations\n    run_migrations_online(target_metadata)\n  File \"/app/share/db/migrations/alembic_env.py\", line 93, in run_migrations_online\n    context.run_migrations()\n  File \"<string>\", line 8, in run_migrations\n  File \"/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py\", line 846, in run_migrations\n    self.get_context().run_migrations(**kw)\n  File \"/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py\", line 522, in run_migrations\n    step.migration_fn(**kw)\n  File \"/app/data_flows_service/db/migrations/versions/2020-12-26 11-13-02_test.py\", line 27, in upgrade\n    op.create_index('ix_created_at', 'test', [sa.text('created_at desc')], unique=True)\n  File \"<string>\", line 8, in create_index\n  File \"<string>\", line 3, in create_index\n  File \"/usr/local/lib/python3.8/site-packages/alembic/operations/ops.py\", line 979, in create_index\n    return operations.invoke(op)\n  File \"/usr/local/lib/python3.8/site-packages/alembic/operations/base.py\", line 373, in invoke\n    return fn(self, operation)\n  File \"/usr/local/lib/python3.8/site-packages/alembic/operations/toimpl.py\", line 88, in create_index\n    operations.impl.create_index(idx)\n  File \"/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py\", line 283, in create_index\n    self._exec(schema.CreateIndex(index))\n  File \"/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py\", line 141, in _exec\n    return conn.execute(construct, *multiparams, **params)\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1011, in execute\n    return meth(self, multiparams, params)\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py\", line 72, in _execute_on_connection\n    return connection._execute_ddl(self, multiparams, params)\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1068, in _execute_ddl\n    ret = self._execute_context(\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1316, in _execute_context\n    self._handle_dbapi_exception(\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1510, in _handle_dbapi_exception\n    util.raise_(\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n    raise exception\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 593, in do_execute\n    cursor.execute(statement, parameters)\n  File \"/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py\", line 206, in execute\n    res = self._query(query)\n  File \"/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py\", line 319, in _query\n    db.query(q)\n  File \"/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py\", line 259, in query\n    _mysql.connection.query(self, query)\nsqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc))' at line 1\")\n[SQL: CREATE UNIQUE INDEX ix_created_at ON test ((created_at desc))]\n(Background on this error at: http://sqlalche.me/e/13/f405)\n"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc))' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/share/db/migrations/utils.py", line 29, in run_db_migrations
    command.upgrade(alembic_cfg, "head")
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "data_flows_service/db/migrations/env.py", line 4, in <module>
    run_migrations(target_metadata=metadata)
  File "/app/share/db/migrations/alembic_env.py", line 100, in run_migrations
    run_migrations_online(target_metadata)
  File "/app/share/db/migrations/alembic_env.py", line 93, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/app/data_flows_service/db/migrations/versions/2020-12-26 11-13-02_test.py", line 27, in upgrade
    op.create_index('ix_created_at', 'test', [sa.text('created_at desc')], unique=True)
  File "<string>", line 8, in create_index
  File "<string>", line 3, in create_index
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/ops.py", line 979, in create_index
    return operations.invoke(op)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 88, in create_index
    operations.impl.create_index(idx)
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 283, in create_index
    self._exec(schema.CreateIndex(index))
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc))' at line 1")
[SQL: CREATE UNIQUE INDEX ix_created_at ON test ((created_at desc))]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: debian 10.6
 - Python: 3.8.6
- Alembic: 1.4.3
- SQLAlchemy: 1.3.20 (and sqlalchemy_utils: 0.36.8, mysqlclient: 2.0.1)
- Database: mysql 8.0.18
- DBAPI: sqlalchemy

**Additional context**
With 
```
mysqlclient==1.3.14
sqlalchemy==1.3.11 
sqlalchemy_utils==0.35.0
alembic==1.3.1
```
the same example does not generate an exception

**Comment by zzzeek** [comment]
not an alembic issue, sqlalchemy https://github.com/sqlalchemy/sqlalchemy/issues/5800

**Comment by zzzeek** [comment]
regression in SQLAlhcemy 1.3.20, use 1.3.19 for now
