### ISSUE TITLE
Unable to bulk insert UUIDs

### ISSUE THREAD

**Issue by sronsiek** [sqlalchemy/alembic#774]
I'm running into an issue trying to bulk_insert data containing UUID objects into a table. The following code in a migration works as expected:

```
import uuid 

def upgrade():

    table = op.create_table( 'alembic_test',
                             sa.Column('id', sa.Integer, primary_key=True),
                             sa.Column('uuid', postgresql.UUID(as_uuid=True))
                           )

    for c in table.c:
        print(repr(c))

    data = [ { 'uuid':  uuid.UUID('f0070679-45fd-4c65-a00c-621d08afa3e6') } ]

    print(repr(data))

    op.bulk_insert(table, data)
```
The printed output is:
```
Column('id', Integer(), table=<alembic_test>, primary_key=True, nullable=False)
Column('uuid', UUID(as_uuid=True), table=<alembic_test>)
[{'uuid': UUID('f0070679-45fd-4c65-a00c-621d08afa3e6')}]
```

The above works when the table object is returned by `op.create_table()`.

However in the case where the table pre-exists, I need to obtain a table object by other means.
The modified migrtion looks like this:

```
import uuid 

def upgrade():

    meta = sa.MetaData(bind=op.get_bind())
    table = sa.Table('alembic_test', meta, autoload=True)

    for c in table.c:
        print(repr(c))

    data = [ { 'uuid':  uuid.UUID('f0070679-45fd-4c65-a00c-621d08afa3e6') } ]

    print(repr(data))

    op.bulk_insert(table, data)
```
The printed output is:
```
Column('id', INTEGER(), table=<alembic_test>, primary_key=True, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7ff9fdaaafd0>, for_update=False))
Column('uuid', UUID(), table=<alembic_test>)
[{'uuid': UUID('f0070679-45fd-4c65-a00c-621d08afa3e6')}]
```

Note the column dump for the uuid col is now missing it's arg, ie original `UUID(as_uuid=True)` is now just `UUID()`.
I believe this what then causes the bulk insert to fail ( stack dump below). Manually converting the uuid to a str also resovled the issue - but ultemately I want to use this pattern to clone table content - which is broken:

```
    conn = op.get_bind()
    res = conn.execute("select * from {}".format(table.name))
    results = res.fetchall()

    data = []
    for row in results:
        data.append( dict(row) )
    op.bulk_insert(tmp_table, data)
```

So, the qu is am I doing something wrong in the way I instanciate the table object ? Why is the UUID arg 'lost'? 
 
The error stack:
```
INFO  [alembic.runtime.migration] Running upgrade 003 -> 004, comments pk to id
Column('id', INTEGER(), table=<alembic_test>, primary_key=True, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7ff9fdaaafd0>, for_update=False))
Column('uuid', UUID(), table=<alembic_test>)
[{'uuid': UUID('f0070679-45fd-4c65-a00c-621d08afa3e6')}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 881, in _init_compiled
    for key in compiled_params
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 881, in <genexpr>
    for key in compiled_params
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 594, in process
    value = _python_UUID(value)
  File "/usr/local/lib/python3.5/uuid.py", line 137, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'UUID' object has no attribute 'replace'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.5/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.5/site-packages/alembic/config.py", line 555, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.5/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.5/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.5/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/logbook/migrations/alembic/env.py", line 88, in <module>
    run_migrations_online()
  File "/opt/logbook/migrations/alembic/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.5/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.5/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/opt/logbook/migrations/alembic/versions/004_comments_pk_to_id.py", line 80, in upgrade
    op.bulk_insert(table, data)
  File "<string>", line 8, in bulk_insert
  File "<string>", line 3, in bulk_insert
  File "/usr/local/lib/python3.5/site-packages/alembic/operations/ops.py", line 2165, in bulk_insert
    operations.invoke(op)
  File "/usr/local/lib/python3.5/site-packages/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.5/site-packages/alembic/operations/toimpl.py", line 171, in bulk_insert
    operation.table, operation.rows, multiinsert=operation.multiinsert
  File "/usr/local/lib/python3.5/site-packages/alembic/ddl/impl.py", line 327, in bulk_insert
    self._exec(table.insert(inline=True), multiparams=rows)
  File "/usr/local/lib/python3.5/site-packages/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1207, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 881, in _init_compiled
    for key in compiled_params
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 881, in <genexpr>
    for key in compiled_params
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 594, in process
    value = _python_UUID(value)
  File "/usr/local/lib/python3.5/uuid.py", line 137, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'UUID' object has no attribute 'replace'
[SQL: INSERT INTO alembic_test (uuid) VALUES (%(uuid)s)]
[parameters: [{'uuid': UUID('f0070679-45fd-4c65-a00c-621d08afa3e6')}]]
```

**Comment by zzzeek** [comment]
this is a SQLAlchemy reflection question.  as_uuid defaults to False so when you reflect the table you must override the type:


    table = sa.Table('alembic_test', meta, sa.Column('uuid', postgresql.UUID(as_uuid=True), autoload=True)


docs for this pattern are at:  https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns

**Comment by sronsiek** [comment]
I wasn't sure - sorry.

I there also a way to override for all UUIDs rather than specifying col name?

**Comment by zzzeek** [comment]
yes there's an event hook https://docs.sqlalchemy.org/en/13/core/events.html?highlight=column_reflect#sqlalchemy.events.DDLEvents.column_reflect , which in 1.3 you can use like this:

```
def receive_column_reflect(inspector, table, column_info):
    if isinstance(column_info['type'], UUID):
        column_info['type'].as_uuid = True

t1 = Table(
    "my_table",
    autoload_with=some_engine,
    listeners=[
        ('column_reflect', receive_column_reflect)
    ]
)
```

the event can also be applied to the Table class overall.  In 1.4 you can apply the event to a specific MetaData().   for this case, any style is sufficient.

**Comment by sronsiek** [comment]
Perfect - working - many thanks!
