### ISSUE TITLE
AttributeError: 'Identity' object has no attribute 'arg' when autogenerating migration on Postgres table with identity columns

### ISSUE THREAD

**Issue by TV4Fun** [sqlalchemy/alembic#775]
**Describe the bug**
Trying to autogenerate a migration on a Postgres table with an `Identity` column produces an `AttributeError` from Alembic. It seems to be assuming the `server_default` member of the `Identity` column has an `arg` member that it doesn't have. Not sure whether that should be classified as an Alembic bug or a SQLAlchemy bug.

**Expected behavior**
Alembic should generate a migration without any errors.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

On a cursory glance, it appears to require a Posgres table with an `Identity` column, and a matching identity column in an equivalent metadata table. A simple way to reproduce this is as follows:

1. Create a test database:
```pgsql
create database test_id with owner postgres;
```
2. Connect to the database and create a test table with an `Identity` column:
```pgsql
create table table_name
(
	id integer generated always as identity
);
```
3. Create a matching schema in SQLAlchemy:
```py
import sqlalchemy
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class TableName(Base):
    __tablename__ = 'table_name'
    id = sqlalchemy.Column(sqlalchemy.Integer, sqlalchemy.Identity(), primary_key=True)
```
4. Setup environment in Alembic, set `sqlalchemy.url` in your `alembic.ini` to point to Test DB, set `target_metadata = Base.metadata` in your `env.py`.
5. Try to autogenerate a revision:
```shell
alembic revision --autogenerate
```

**Error**

```shell
(venv) C:\Users\jcrot\PycharmProjects\complex_systems_sqlalchemy>alembic revision --autogenerate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "C:\Users\jcrot\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jcrot\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jcrot\PycharmProjects\complex_systems_sqlalchemy\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\config.py", line 552, in run_cmd
    fn(
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\command.py", line 214, in revision
    script_directory.run_env()
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\script\base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\util\pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic\env.py", line 81, in <module>
    run_migrations_online()
  File "alembic\env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\runtime\environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\runtime\migration.py", line 511, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\command.py", line 190, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\api.py", line 442, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\api.py", line 481, in _run_environment
    compare._populate_migration_script(
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\compare.py", line 25, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\compare.py", line 50, in _produce_net_changes
    comparators.dispatch("schema", autogen_context.dialect.name)(
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\util\langhelpers.py", line 303, in go
    fn(*arg, **kw)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\compare.py", line 78, in _autogen_for_tables
    _compare_tables(
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\compare.py", line 209, in _compare_tables
    with _compare_columns(
  File "C:\Users\jcrot\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\compare.py", line 312, in _compare_columns
    comparators.dispatch("column")(
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\util\langhelpers.py", line 303, in go
    fn(*arg, **kw)
  File "c:\users\jcrot\pycharmprojects\complex_systems_sqlalchemy\venv\lib\site-packages\alembic\autogenerate\compare.py", line 1021, in _compare_server_default
    conn_col.server_default.arg.text
AttributeError: 'Identity' object has no attribute 'arg'

```

**Versions.**
 - OS: Windows 10 Pro 19041.685
 - Python: 3.8.6
 - Alembic: 1.4.3
 - SQLAlchemy: 1.4.0b1
 - Database: PostgreSQL 13.0
 - DBAPI: psycopg2 2.8.6

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
identity support is not released yet but is merged into alembic master.   can you try out git master to see if anything is better regarding this?  cc @CaselIT

**Comment by CaselIT** [comment]
As Mike said, support for Identity column is not yet released, but it was added in master in 92b4ed39147aca1d102a2f92bb8dd78580c92c1f

Could you try using master ad report if it works correctly for you?
Thanks

**Comment by zzzeek** [comment]
oh yeah just noticed you are using SQLAlchemy 1.4 betas with Alembic released.   SQLAlchemy 1.4 is held up right now until we can get Alembic 1.5 out.

**Comment by lxmn** [comment]
pip install sqlacodegen==3.0.0b2
worked for me

**Comment by turbcool** [comment]
At the moment sqlacodegen==3.0.0rc2 version is better.

**Comment by hsibanda** [comment]
> At the moment sqlacodegen==3.0.0rc2 version is the newest.

Latest one sill fails for me with sql server. I then tries the suggested 3.0.0b2 and it worked 👌
