### ISSUE TITLE
upgrade database programmatically without template

### ISSUE THREAD

**Issue by flapili** [sqlalchemy/alembic#806]
Hi,
I'm creating a framework based on FastAPI and Gino and I need to create a cli command (I'm using click) which upgrade on the fly the database.

I want avoid the use of the classic template ( env.py / ini file /ect ... )

for now I have
```py
import pprint

from alembic.migration import MigrationContext
# from alembic.autogenerate import compare_metadata
from alembic.autogenerate import produce_migrations
# from sqlalchemy.schema import SchemaItem
# from sqlalchemy.types import TypeEngine
from sqlalchemy import create_engine, MetaData, Column, Integer, String, Table, text



engine = create_engine("sqlite://")

with engine.begin() as conn:
    conn.execute(
        text(
            """
        create table foo (
            id integer not null primary key,
            old_data varchar,
            x integer
        )"""
        )
    )

    conn.execute(
        text(
            """
        create table bar (
            data varchar
        )"""
        )
    )

metadata = MetaData()
Table(
    "foo",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("data", Integer),
    Column("x", Integer, nullable=False),
)
Table("bat", metadata, Column("info", String))

mc = MigrationContext.configure(engine.connect())

migration = produce_migrations(mc, metadata)
pprint.pprint(migration, indent=2, width=20)
pprint.pprint(migration.__dir__())
print(type(migration))
```
But I don't know what to do with `alembic.operations.ops.MigrationScript`

I'm not sure to be in the right way :(
**Have a nice day!**

**edit:**

I trying a different way, I'm inspiring by https://github.com/patiprecios/fastapi-migrations and https://github.com/miguelgrinberg/Flask-Migrate 
```
PS C:\Users\DEVEAUX\Desktop\prog\ModularAPI> python .\modularapi\cli.py
Generating C:\Users\DEVEAUX\Desktop\prog\ModularAPI\versions\c0188f900bb9_test.py ...  FAILED
Traceback (most recent call last):
  File ".\modularapi\cli.py", line 32, in <module>
    r = command.revision(config=alembic_cfg, message="test")
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\command.py", line 221, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\command.py", line 221, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\autogenerate\api.py", line 513, in generate_scripts
    yield self._to_script(generated_revision)
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\autogenerate\api.py", line 429, in _to_script
    return self.script_directory.generate_revision(
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\script\base.py", line 640, in generate_revision
    self._generate_template(
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\script\base.py", line 496, in _generate_template
    util.status(
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\util\messaging.py", line 52, in status
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\alembic\util\pyfiles.py", line 17, in template_to_file
    template = Template(filename=template_file)
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\mako\template.py", line 429, in _compile_from_file
    data = util.read_file(filename)
  File "C:\Users\DEVEAUX\AppData\Local\Programs\Python\Python38\lib\site-packages\mako\util.py", line 383, in read_file
    fp = open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: '.\\script.py.mako
```
the tree:
```
ModularAPI
│   .env
│   poetry.lock
│   pyproject.toml
│   README.rst
│   temp
│
├───.vscode
│       settings.json
│
├───dist
│       ModularAPI-0.0.1-py3-none-any.whl
│       ModularAPI-0.0.1.tar.gz
│
├───modularapi
│   │   app.py
│   │   asgi.py
│   │   cli.py
│   │   db.py
│   │   settings.py
│   │   utils.py
│   │   venv_requirements.txt
│   │   __init__.py
│   │   
│   ├───templates
│   │   └───default
│   │           env.py
│   │           README
│   │           script.py.mako
│   │
│   └───__pycache__
│           utils.cpython-38.pyc
│
├───tests
│       test_modularapi.py
│       __init__.py
│
└───versions
```

and the script:
```py
import sys
import os
import venv
import shutil
import subprocess
import time
import json
from pathlib import Path

import click
import git

from alembic import command
from alembic.config import Config


from modularapi.settings import get_setting
from modularapi.utils import _on_rmtree_error


class AlembicConfig(Config):
    def get_template_directory(self):
        pkg_dir = Path(__file__).resolve().parent
        return pkg_dir / "templates"


(Path() / "versions").mkdir(exist_ok=True)

alembic_cfg = AlembicConfig()
alembic_cfg.set_main_option("sqlalchemy.url", get_setting().PG_DNS)
alembic_cfg.set_main_option("script_location", str(Path()))
r = command.revision(config=alembic_cfg, message="test")
print(r)
exit(0)
```

I don't understand what is the issue :/

**Comment by zzzeek** [comment]
try looking at the example here: https://alembic.sqlalchemy.org/en/latest/cookbook.html#run-alembic-operation-objects-directly-as-in-from-autogenerate

but alembic is not really intended to automatically upgrade a database without manual intervention.  you'd want to look at Django's migrations for that kind of thing.
