### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'configure'` when running migrations

### ISSUE THREAD

**Issue by jtpavlock** [sqlalchemy/alembic#861]
**Describe the bug**
```bash
$ alembic revision --autogenerate -m "added extras"
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/command.py", line 212, in revision
    script_directory.run_env()
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "alembic/env.py", line 66, in <module>
    run_migrations_online()
  File "alembic/env.py", line 60, in run_migrations_online
    context.configure(connection=connection, target_metadata=target_metadata)
  File "<string>", line 8, in configure
AttributeError: 'NoneType' object has no attribute 'configure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jacob/src/Moe/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/config.py", line 530, in run_cmd
    fn(
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/command.py", line 212, in revision
    script_directory.run_env()
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 110, in __exit__
    self._remove_proxy()
  File "/home/jacob/src/Moe/.venv/lib/python3.8/site-packages/alembic/util/langhelpers.py", line 50, in _remove_proxy
    del globals_[attr_name]
KeyError: 'script'
```
 The above error occurs when trying to run a migration

Here's my `env.py`:
```python
from logging.config import fileConfig

from alembic import context
from moe.core.config import Config
from moe.core.library.session import Base

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# don't configure logger if Moe is running
if config.attributes.get("configure_logger", True):
    fileConfig(config.config_file_name)

# add your model's MetaData object here
# for 'autogenerate' support
# from myapp import mymodel
# target_metadata = mymodel.Base.metadata
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine and associate a connection
    with the context.
    """
    connectable = config.attributes.get("connection", None)
    if not connectable:
        # only create Engine if we don't have a Connection from the outside
        moe_config = Config()
        moe_config.init_db()
        connectable = moe_config.engine

    # When connectable is already a Connection object, calling
    # connect() gives us a *branched connection*.
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


run_migrations_online()
```

**Expected behavior**
When autogenerating a migration, no errors to occur.

**To Reproduce**
Working on this. Wanted to see if you had any initial thoughts before trying to create a minimal example.

**Versions.**
 - OS: Ubuntu 20 LTS
 - Python: 3.8
 - Alembic: 1.6.3
 - SQLAlchemy: 1.4.15
 - Database: sqlite
 - DBAPI:

**Additional context**
I'm not sure what changed, but I used to be able to run migrations just fine. I didn't think I had altered any relevant code to the migration process.

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

we just had a similar issue the other day and I would ask that you remove these imports and related code:

```
from moe.core.config import Config
from moe.core.library.session import Base
```

then see if the issue goes away.   review your own application to see that they are not emitting any alembic API calls or command within the "import" phase or related phases of these other modules.
