### ISSUE TITLE
alembic autogenerate migration fails with database file not found error for sqlite

### ISSUE THREAD

**Issue by vikigenius** [sqlalchemy/alembic#898]
**Describe the bug**

Trying to auto-generate migrations fails with database file not found error when sqlite db file does not exist

**Expected behavior**

When an sqlite db is not found a db file should be created based on the url.

**To Reproduce**
1. Initialize alembic with the async template `alembic init alembic --template async`
2. Set `sqlalchemy.url = sqlite+aiosqlite:///home/void/.local/share/redorg/redorg.db`
3. Edit `alembic/env.py` to set target_metadata correctly.
4. Generate migration using `alembic revision -m 'Create user items table' --autogenerate`

I have verified that the directory exists and has write permissions.

Here is my simple model, directly lifted from the SQLAlchemy example
```py
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer, String


Base = declarative_base()


class User(Base):
     __tablename__ = 'users'

     id = Column(Integer, primary_key=True)
     name = Column(String)
     fullname = Column(String)
     nickname = Column(String)

     def __repr__(self):
        return "<User(name='%s', fullname='%s', nickname='%s')>" % (
                             self.name, self.fullname, self.nickname)

```

**Error**

```
Traceback (most recent call last):
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 291, in connect
    await_only(connection),
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 137, in _connect
    self._connection = await future
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 397, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/void/Projects/Python/albug/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/command.py", line 227, in revision
    script_directory.run_env()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "alembic/env.py", line 84, in <module>
    asyncio.run(run_migrations_online())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "alembic/env.py", line 77, in run_migrations_online
    async with connectable.connect() as connection:
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/base.py", line 57, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 106, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 419, in connect
    return super(Engine, self).connect()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2069, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 291, in connect
    await_only(connection),
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 137, in _connect
    self._connection = await future
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/home/void/Projects/Python/albug/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 397, in connector
    return sqlite3.connect(loc, **kwargs)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Versions.**
 - OS: Linux x86_64
 - Python: 3.9.7
 - Alembic: 1.7.1
 - SQLAlchemy: 1.4.23
 - Database: sqlite
 - DBAPI: aiosqlite

**Comment by vikigenius** [comment]
Ok it was definitely an issue from my side. I missed a leading `/` Since I am including the full path the db url should have been

`sqlite+aiosqlite:////home/void/.local/share/redorg/redorg.db`
