### ISSUE TITLE
Missing module importlib_resources breaks migrations

### ISSUE THREAD

**Issue by ebozkurt93** [sqlalchemy/alembic#955]
**Describe the bug**
Alembic 1.7.4 on Python 3.8 requires `importlib-resources`, and the migration fails.

**Expected behavior**
Ideally alembic should check and try to use `importlib.resources` for python >= 3.7, [since it might be already there](https://pypi.org/project/importlib-resources/), worst case `importlib-resources` should be a subdependency for alembic.

FYI, locally I've modified line 28 [here](https://github.com/sqlalchemy/alembic/blob/rel_1_7_4/alembic/util/compat.py#L11-L36) to support `py38`, everything worked afterwards.

**Error**

```
Traceback (most recent call last):
  File "db_manager.py", line 5, in <module>
    from flask_migrate import Migrate, MigrateCommand
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/flask_migrate/__init__.py", line 11, in <module>
    from alembic import __version__ as __alembic_version__
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/runtime/environment.py", line 12, in <module>
    from .migration import MigrationContext
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/runtime/migration.py", line 27, in <module>
    from .. import ddl
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/ddl/mssql.py", line 14, in <module>
    from .base import AddColumn
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/ddl/base.py", line 14, in <module>
    from ..util.sqla_compat import _columns_for_constraint  # noqa
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/util/__init__.py", line 1, in <module>
    from .editor import open_in_editor
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/util/editor.py", line 11, in <module>
    from .compat import is_posix
  File "/Users/erdembozkurt/.local/share/virtualenvs/backend-N-woTSGu/lib/python3.8/site-packages/alembic/util/compat.py", line 33, in <module>
    import importlib_resources  # type:ignore[no-redef] # noqa
ModuleNotFoundError: No module named 'importlib_resources'
```

**Versions.**
 - OS: MacOS 
 - Python: 3.8.6
 - Alembic: 1.7.4
 - SQLAlchemy: 1.3.23
 - Database: Postgres 9.6

**Comment by zzzeek** [comment]
resources/), worst case `importlib-resources` and `importlib-metadata` should be a subdependency for alembic.

they are, as seen here:

https://github.com/sqlalchemy/alembic/blob/888fa838c824e9127eeb3d748c19df5da419748c/setup.cfg#L42-L46
