### ISSUE TITLE
Other sections than [alembic] are read from the ini file

### ISSUE THREAD

**Issue by elsampsa** [sqlalchemy/alembic#985]
**Describe the bug**
I have an .ini file with ``[alembic]`` section.  So far so good..  But if the ini file is missing ``[handlers]`` section (or any of the sections related to logging, to that matter), ``alembic -c mycustom.ini upgrade head`` fails, with ``KeyError``s.

**Expected behavior**
Alembic docs, and I quote, say:
> [alembic] - this is the section read by Alembic to determine configuration. Alembic itself does not directly read any other areas of the file.

So missing those mentioned section should not be a problem

**To Reproduce**
Create any .ini file missing the ``[handlers]`` section (or any of the loggin sections), feed that ini file to ``alembic upgrade head`` and the bug will appear.

# Copy error here. Please include the full stack trace.
```
**Versions.**
 - OS: Linux
 - Python: 3.8
 - Alembic: 1.7.6
 - SQLAlchemy: (not relevant)
 - Database: (not relevant)
 - DBAPI: (not relevant)
```
```
Traceback (most recent call last):
  File "/home/sampsa/.local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/sampsa/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sampsa/silo/my-fast-api/backend/app/app/api_v1/alembic/env.py", line 14, in <module>
    fileConfig(config.config_file_name)
  File "/usr/lib/python3.8/logging/config.py", line 79, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python3.8/logging/config.py", line 126, in _install_handlers
    hlist = cp["handlers"]["keys"]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'handlers'
```
**Have a nice day!**

*you too!*

**Comment by elsampsa** [comment]
a bonus question: is there a way to enable ``configparser.ExtendedInterpolation`` for the ini files.. then I could do this:
```
sqlalchemy.url = postgres://${Postgres:user}:${Postgres:password}@${Postgres:adr}:${Postgres:port}/${Postgres:database_name}
```

**Comment by zzzeek** [comment]
alembic is in fact not reading those entries from the file.  but, it's a trick question.  if you look in your stack trace:

File "/home/sampsa/silo/my-fast-api/backend/app/app/api_v1/alembic/env.py", line 14, in <module>
    fileConfig(config.config_file_name)

that `env.py` , while generated from Alembic is in **your** application.  you should [adjust it to suit your needs](https://alembic.sqlalchemy.org/en/latest/tutorial.html#the-migration-environment).

Will modify the above sentence to clarify this.
